name: 'bump'

on:
  push:
    branches: [ 'main' ]

jobs:
  bump:
    if: |
         !contains(github.event.head_commit.message, 'bump')
         && !contains(github.event.head_commit.message, 'ci')
         && !contains(github.event.head_commit.message, '[NO_PUB]')
    runs-on: 'ubuntu-latest'
    steps:

    # Setup
    - uses: 'actions/setup-node@v1'
      with: { node-version: '14' }

    - uses: 'actions/checkout@v2'
      with:
        token: ${{ secrets.GITHUB_PAT }}

    - run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

    # run `standard-version`
    # - update CHANGELOG,
    # - create version tag
    # - create version commits
    - run: 'npx standard-version'

    # Cargo Check
    # - update version in Cargo.lock
    # - make sure code's buildable
    - name: 'ensure Cargo.lock fresh'
      run: 'cargo c'

    # Push changes to main
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
      run: 'git push'

    # Push the new tag
    # - triggers 'publish' job
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
      run: 'git push --tags'
